[tox]
envlist = py312, lint, format
isolated_build = True

[testenv]
description = run all unit tests
deps =
    pytest
commands =
    pytest {posargs:pareto_designer/tests/}

[testenv:lint]
description = run ruff linting
skip_install = true
deps =
    ruff
commands =
    ruff check {posargs:.}

[testenv:format]
description = run black formatting
skip_install = true
deps =
    black
commands =
    black {posargs:pareto_designer scripts}